# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0002_user_pokes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_poke', to='login_app.User')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poked', to='login_app.User')),
            ],
        ),
    ]
